[versions]
cdk = "2.9"
kotlin = "2.0.0"
ktor = "3.0.0-beta-1"
logback = "1.4.14"

[libraries]
cdk = { group = "org.openscience.cdk", name = "cdk-bundle", version.ref = "cdk" }
ktor-jvm = { group = "io.ktor", name = "ktor-server-core-jvm" }
ktor-tests = { group = "io.ktor", name = "ktor-server-tests-jvm" }
ktor-netty = { group = "io.ktor", name = "ktor-server-netty-jvm" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

[bundles]
